# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/langa/project214/Chaos_Compilers_COS214_Project_2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/langa/project214/Chaos_Compilers_COS214_Project_2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/langa/project214/Chaos_Compilers_COS214_Project_2025/CMakeFiles /home/langa/project214/Chaos_Compilers_COS214_Project_2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/langa/project214/Chaos_Compilers_COS214_Project_2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project_lib

# Build rule for target.
project_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_lib
.PHONY : project_lib

# fast build rule for target.
project_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/build
.PHONY : project_lib/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named project_lib_autogen_timestamp_deps

# Build rule for target.
project_lib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_lib_autogen_timestamp_deps
.PHONY : project_lib_autogen_timestamp_deps

# fast build rule for target.
project_lib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib_autogen_timestamp_deps.dir/build.make CMakeFiles/project_lib_autogen_timestamp_deps.dir/build
.PHONY : project_lib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named project_lib_autogen

# Build rule for target.
project_lib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_lib_autogen
.PHONY : project_lib_autogen

# fast build rule for target.
project_lib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib_autogen.dir/build.make CMakeFiles/project_lib_autogen.dir/build
.PHONY : project_lib_autogen/fast

#=============================================================================
# Target rules for targets named run_tests_autogen_timestamp_deps

# Build rule for target.
run_tests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests_autogen_timestamp_deps
.PHONY : run_tests_autogen_timestamp_deps

# fast build rule for target.
run_tests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests_autogen_timestamp_deps.dir/build.make CMakeFiles/run_tests_autogen_timestamp_deps.dir/build
.PHONY : run_tests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named run_tests_autogen

# Build rule for target.
run_tests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests_autogen
.PHONY : run_tests_autogen

# fast build rule for target.
run_tests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests_autogen.dir/build.make CMakeFiles/run_tests_autogen.dir/build
.PHONY : run_tests_autogen/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock_autogen_timestamp_deps

# Build rule for target.
gmock_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen_timestamp_deps
.PHONY : gmock_autogen_timestamp_deps

# fast build rule for target.
gmock_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen_timestamp_deps.dir/build
.PHONY : gmock_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_autogen

# Build rule for target.
gmock_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_autogen
.PHONY : gmock_autogen

# fast build rule for target.
gmock_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_autogen.dir/build
.PHONY : gmock_autogen/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen_timestamp_deps

# Build rule for target.
gmock_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen_timestamp_deps
.PHONY : gmock_main_autogen_timestamp_deps

# fast build rule for target.
gmock_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen_timestamp_deps.dir/build
.PHONY : gmock_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gmock_main_autogen

# Build rule for target.
gmock_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main_autogen
.PHONY : gmock_main_autogen

# fast build rule for target.
gmock_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main_autogen.dir/build
.PHONY : gmock_main_autogen/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest_autogen_timestamp_deps

# Build rule for target.
gtest_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen_timestamp_deps
.PHONY : gtest_autogen_timestamp_deps

# fast build rule for target.
gtest_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_autogen_timestamp_deps.dir/build
.PHONY : gtest_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_autogen

# Build rule for target.
gtest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_autogen
.PHONY : gtest_autogen

# fast build rule for target.
gtest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_autogen.dir/build
.PHONY : gtest_autogen/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen_timestamp_deps

# Build rule for target.
gtest_main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen_timestamp_deps
.PHONY : gtest_main_autogen_timestamp_deps

# fast build rule for target.
gtest_main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen_timestamp_deps.dir/build
.PHONY : gtest_main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named gtest_main_autogen

# Build rule for target.
gtest_main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main_autogen
.PHONY : gtest_main_autogen

# fast build rule for target.
gtest_main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main_autogen.dir/build
.PHONY : gtest_main_autogen/fast

#=============================================================================
# Target rules for targets named Nursery

# Build rule for target.
Nursery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nursery
.PHONY : Nursery

# fast build rule for target.
Nursery/fast:
	$(MAKE) $(MAKESILENT) -f src/Nursery/CMakeFiles/Nursery.dir/build.make src/Nursery/CMakeFiles/Nursery.dir/build
.PHONY : Nursery/fast

#=============================================================================
# Target rules for targets named Nursery_autogen_timestamp_deps

# Build rule for target.
Nursery_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nursery_autogen_timestamp_deps
.PHONY : Nursery_autogen_timestamp_deps

# fast build rule for target.
Nursery_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/Nursery/CMakeFiles/Nursery_autogen_timestamp_deps.dir/build.make src/Nursery/CMakeFiles/Nursery_autogen_timestamp_deps.dir/build
.PHONY : Nursery_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Nursery_autogen

# Build rule for target.
Nursery_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nursery_autogen
.PHONY : Nursery_autogen

# fast build rule for target.
Nursery_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/Nursery/CMakeFiles/Nursery_autogen.dir/build.make src/Nursery/CMakeFiles/Nursery_autogen.dir/build
.PHONY : Nursery_autogen/fast

project_lib_autogen/mocs_compilation.o: project_lib_autogen/mocs_compilation.cpp.o
.PHONY : project_lib_autogen/mocs_compilation.o

# target to build an object file
project_lib_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/project_lib_autogen/mocs_compilation.cpp.o
.PHONY : project_lib_autogen/mocs_compilation.cpp.o

project_lib_autogen/mocs_compilation.i: project_lib_autogen/mocs_compilation.cpp.i
.PHONY : project_lib_autogen/mocs_compilation.i

# target to preprocess a source file
project_lib_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/project_lib_autogen/mocs_compilation.cpp.i
.PHONY : project_lib_autogen/mocs_compilation.cpp.i

project_lib_autogen/mocs_compilation.s: project_lib_autogen/mocs_compilation.cpp.s
.PHONY : project_lib_autogen/mocs_compilation.s

# target to generate assembly for a file
project_lib_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/project_lib_autogen/mocs_compilation.cpp.s
.PHONY : project_lib_autogen/mocs_compilation.cpp.s

run_tests_autogen/mocs_compilation.o: run_tests_autogen/mocs_compilation.cpp.o
.PHONY : run_tests_autogen/mocs_compilation.o

# target to build an object file
run_tests_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/run_tests_autogen/mocs_compilation.cpp.o
.PHONY : run_tests_autogen/mocs_compilation.cpp.o

run_tests_autogen/mocs_compilation.i: run_tests_autogen/mocs_compilation.cpp.i
.PHONY : run_tests_autogen/mocs_compilation.i

# target to preprocess a source file
run_tests_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/run_tests_autogen/mocs_compilation.cpp.i
.PHONY : run_tests_autogen/mocs_compilation.cpp.i

run_tests_autogen/mocs_compilation.s: run_tests_autogen/mocs_compilation.cpp.s
.PHONY : run_tests_autogen/mocs_compilation.s

# target to generate assembly for a file
run_tests_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/run_tests_autogen/mocs_compilation.cpp.s
.PHONY : run_tests_autogen/mocs_compilation.cpp.s

src/Customer/Browse.o: src/Customer/Browse.cpp.o
.PHONY : src/Customer/Browse.o

# target to build an object file
src/Customer/Browse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Browse.cpp.o
.PHONY : src/Customer/Browse.cpp.o

src/Customer/Browse.i: src/Customer/Browse.cpp.i
.PHONY : src/Customer/Browse.i

# target to preprocess a source file
src/Customer/Browse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Browse.cpp.i
.PHONY : src/Customer/Browse.cpp.i

src/Customer/Browse.s: src/Customer/Browse.cpp.s
.PHONY : src/Customer/Browse.s

# target to generate assembly for a file
src/Customer/Browse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Browse.cpp.s
.PHONY : src/Customer/Browse.cpp.s

src/Customer/Customer.o: src/Customer/Customer.cpp.o
.PHONY : src/Customer/Customer.o

# target to build an object file
src/Customer/Customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Customer.cpp.o
.PHONY : src/Customer/Customer.cpp.o

src/Customer/Customer.i: src/Customer/Customer.cpp.i
.PHONY : src/Customer/Customer.i

# target to preprocess a source file
src/Customer/Customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Customer.cpp.i
.PHONY : src/Customer/Customer.cpp.i

src/Customer/Customer.s: src/Customer/Customer.cpp.s
.PHONY : src/Customer/Customer.s

# target to generate assembly for a file
src/Customer/Customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Customer.cpp.s
.PHONY : src/Customer/Customer.cpp.s

src/Customer/CustomerCreator.o: src/Customer/CustomerCreator.cpp.o
.PHONY : src/Customer/CustomerCreator.o

# target to build an object file
src/Customer/CustomerCreator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/CustomerCreator.cpp.o
.PHONY : src/Customer/CustomerCreator.cpp.o

src/Customer/CustomerCreator.i: src/Customer/CustomerCreator.cpp.i
.PHONY : src/Customer/CustomerCreator.i

# target to preprocess a source file
src/Customer/CustomerCreator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/CustomerCreator.cpp.i
.PHONY : src/Customer/CustomerCreator.cpp.i

src/Customer/CustomerCreator.s: src/Customer/CustomerCreator.cpp.s
.PHONY : src/Customer/CustomerCreator.s

# target to generate assembly for a file
src/Customer/CustomerCreator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/CustomerCreator.cpp.s
.PHONY : src/Customer/CustomerCreator.cpp.s

src/Customer/Enquire.o: src/Customer/Enquire.cpp.o
.PHONY : src/Customer/Enquire.o

# target to build an object file
src/Customer/Enquire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Enquire.cpp.o
.PHONY : src/Customer/Enquire.cpp.o

src/Customer/Enquire.i: src/Customer/Enquire.cpp.i
.PHONY : src/Customer/Enquire.i

# target to preprocess a source file
src/Customer/Enquire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Enquire.cpp.i
.PHONY : src/Customer/Enquire.cpp.i

src/Customer/Enquire.s: src/Customer/Enquire.cpp.s
.PHONY : src/Customer/Enquire.s

# target to generate assembly for a file
src/Customer/Enquire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Enquire.cpp.s
.PHONY : src/Customer/Enquire.cpp.s

src/Customer/Purchasing.o: src/Customer/Purchasing.cpp.o
.PHONY : src/Customer/Purchasing.o

# target to build an object file
src/Customer/Purchasing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Purchasing.cpp.o
.PHONY : src/Customer/Purchasing.cpp.o

src/Customer/Purchasing.i: src/Customer/Purchasing.cpp.i
.PHONY : src/Customer/Purchasing.i

# target to preprocess a source file
src/Customer/Purchasing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Purchasing.cpp.i
.PHONY : src/Customer/Purchasing.cpp.i

src/Customer/Purchasing.s: src/Customer/Purchasing.cpp.s
.PHONY : src/Customer/Purchasing.s

# target to generate assembly for a file
src/Customer/Purchasing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Customer/Purchasing.cpp.s
.PHONY : src/Customer/Purchasing.cpp.s

src/Greenhouse/AddStock.o: src/Greenhouse/AddStock.cpp.o
.PHONY : src/Greenhouse/AddStock.o

# target to build an object file
src/Greenhouse/AddStock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AddStock.cpp.o
.PHONY : src/Greenhouse/AddStock.cpp.o

src/Greenhouse/AddStock.i: src/Greenhouse/AddStock.cpp.i
.PHONY : src/Greenhouse/AddStock.i

# target to preprocess a source file
src/Greenhouse/AddStock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AddStock.cpp.i
.PHONY : src/Greenhouse/AddStock.cpp.i

src/Greenhouse/AddStock.s: src/Greenhouse/AddStock.cpp.s
.PHONY : src/Greenhouse/AddStock.s

# target to generate assembly for a file
src/Greenhouse/AddStock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AddStock.cpp.s
.PHONY : src/Greenhouse/AddStock.cpp.s

src/Greenhouse/Autumn.o: src/Greenhouse/Autumn.cpp.o
.PHONY : src/Greenhouse/Autumn.o

# target to build an object file
src/Greenhouse/Autumn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Autumn.cpp.o
.PHONY : src/Greenhouse/Autumn.cpp.o

src/Greenhouse/Autumn.i: src/Greenhouse/Autumn.cpp.i
.PHONY : src/Greenhouse/Autumn.i

# target to preprocess a source file
src/Greenhouse/Autumn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Autumn.cpp.i
.PHONY : src/Greenhouse/Autumn.cpp.i

src/Greenhouse/Autumn.s: src/Greenhouse/Autumn.cpp.s
.PHONY : src/Greenhouse/Autumn.s

# target to generate assembly for a file
src/Greenhouse/Autumn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Autumn.cpp.s
.PHONY : src/Greenhouse/Autumn.cpp.s

src/Greenhouse/AutumnCommand.o: src/Greenhouse/AutumnCommand.cpp.o
.PHONY : src/Greenhouse/AutumnCommand.o

# target to build an object file
src/Greenhouse/AutumnCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AutumnCommand.cpp.o
.PHONY : src/Greenhouse/AutumnCommand.cpp.o

src/Greenhouse/AutumnCommand.i: src/Greenhouse/AutumnCommand.cpp.i
.PHONY : src/Greenhouse/AutumnCommand.i

# target to preprocess a source file
src/Greenhouse/AutumnCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AutumnCommand.cpp.i
.PHONY : src/Greenhouse/AutumnCommand.cpp.i

src/Greenhouse/AutumnCommand.s: src/Greenhouse/AutumnCommand.cpp.s
.PHONY : src/Greenhouse/AutumnCommand.s

# target to generate assembly for a file
src/Greenhouse/AutumnCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/AutumnCommand.cpp.s
.PHONY : src/Greenhouse/AutumnCommand.cpp.s

src/Greenhouse/CareStrategy.o: src/Greenhouse/CareStrategy.cpp.o
.PHONY : src/Greenhouse/CareStrategy.o

# target to build an object file
src/Greenhouse/CareStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/CareStrategy.cpp.o
.PHONY : src/Greenhouse/CareStrategy.cpp.o

src/Greenhouse/CareStrategy.i: src/Greenhouse/CareStrategy.cpp.i
.PHONY : src/Greenhouse/CareStrategy.i

# target to preprocess a source file
src/Greenhouse/CareStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/CareStrategy.cpp.i
.PHONY : src/Greenhouse/CareStrategy.cpp.i

src/Greenhouse/CareStrategy.s: src/Greenhouse/CareStrategy.cpp.s
.PHONY : src/Greenhouse/CareStrategy.s

# target to generate assembly for a file
src/Greenhouse/CareStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/CareStrategy.cpp.s
.PHONY : src/Greenhouse/CareStrategy.cpp.s

src/Greenhouse/Command.o: src/Greenhouse/Command.cpp.o
.PHONY : src/Greenhouse/Command.o

# target to build an object file
src/Greenhouse/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Command.cpp.o
.PHONY : src/Greenhouse/Command.cpp.o

src/Greenhouse/Command.i: src/Greenhouse/Command.cpp.i
.PHONY : src/Greenhouse/Command.i

# target to preprocess a source file
src/Greenhouse/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Command.cpp.i
.PHONY : src/Greenhouse/Command.cpp.i

src/Greenhouse/Command.s: src/Greenhouse/Command.cpp.s
.PHONY : src/Greenhouse/Command.s

# target to generate assembly for a file
src/Greenhouse/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Command.cpp.s
.PHONY : src/Greenhouse/Command.cpp.s

src/Greenhouse/Dead.o: src/Greenhouse/Dead.cpp.o
.PHONY : src/Greenhouse/Dead.o

# target to build an object file
src/Greenhouse/Dead.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Dead.cpp.o
.PHONY : src/Greenhouse/Dead.cpp.o

src/Greenhouse/Dead.i: src/Greenhouse/Dead.cpp.i
.PHONY : src/Greenhouse/Dead.i

# target to preprocess a source file
src/Greenhouse/Dead.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Dead.cpp.i
.PHONY : src/Greenhouse/Dead.cpp.i

src/Greenhouse/Dead.s: src/Greenhouse/Dead.cpp.s
.PHONY : src/Greenhouse/Dead.s

# target to generate assembly for a file
src/Greenhouse/Dead.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Dead.cpp.s
.PHONY : src/Greenhouse/Dead.cpp.s

src/Greenhouse/FlowerPlant.o: src/Greenhouse/FlowerPlant.cpp.o
.PHONY : src/Greenhouse/FlowerPlant.o

# target to build an object file
src/Greenhouse/FlowerPlant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlant.cpp.o
.PHONY : src/Greenhouse/FlowerPlant.cpp.o

src/Greenhouse/FlowerPlant.i: src/Greenhouse/FlowerPlant.cpp.i
.PHONY : src/Greenhouse/FlowerPlant.i

# target to preprocess a source file
src/Greenhouse/FlowerPlant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlant.cpp.i
.PHONY : src/Greenhouse/FlowerPlant.cpp.i

src/Greenhouse/FlowerPlant.s: src/Greenhouse/FlowerPlant.cpp.s
.PHONY : src/Greenhouse/FlowerPlant.s

# target to generate assembly for a file
src/Greenhouse/FlowerPlant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlant.cpp.s
.PHONY : src/Greenhouse/FlowerPlant.cpp.s

src/Greenhouse/FlowerPlanter.o: src/Greenhouse/FlowerPlanter.cpp.o
.PHONY : src/Greenhouse/FlowerPlanter.o

# target to build an object file
src/Greenhouse/FlowerPlanter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlanter.cpp.o
.PHONY : src/Greenhouse/FlowerPlanter.cpp.o

src/Greenhouse/FlowerPlanter.i: src/Greenhouse/FlowerPlanter.cpp.i
.PHONY : src/Greenhouse/FlowerPlanter.i

# target to preprocess a source file
src/Greenhouse/FlowerPlanter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlanter.cpp.i
.PHONY : src/Greenhouse/FlowerPlanter.cpp.i

src/Greenhouse/FlowerPlanter.s: src/Greenhouse/FlowerPlanter.cpp.s
.PHONY : src/Greenhouse/FlowerPlanter.s

# target to generate assembly for a file
src/Greenhouse/FlowerPlanter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerPlanter.cpp.s
.PHONY : src/Greenhouse/FlowerPlanter.cpp.s

src/Greenhouse/FlowerStrategy.o: src/Greenhouse/FlowerStrategy.cpp.o
.PHONY : src/Greenhouse/FlowerStrategy.o

# target to build an object file
src/Greenhouse/FlowerStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerStrategy.cpp.o
.PHONY : src/Greenhouse/FlowerStrategy.cpp.o

src/Greenhouse/FlowerStrategy.i: src/Greenhouse/FlowerStrategy.cpp.i
.PHONY : src/Greenhouse/FlowerStrategy.i

# target to preprocess a source file
src/Greenhouse/FlowerStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerStrategy.cpp.i
.PHONY : src/Greenhouse/FlowerStrategy.cpp.i

src/Greenhouse/FlowerStrategy.s: src/Greenhouse/FlowerStrategy.cpp.s
.PHONY : src/Greenhouse/FlowerStrategy.s

# target to generate assembly for a file
src/Greenhouse/FlowerStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/FlowerStrategy.cpp.s
.PHONY : src/Greenhouse/FlowerStrategy.cpp.s

src/Greenhouse/GiftWrap.o: src/Greenhouse/GiftWrap.cpp.o
.PHONY : src/Greenhouse/GiftWrap.o

# target to build an object file
src/Greenhouse/GiftWrap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/GiftWrap.cpp.o
.PHONY : src/Greenhouse/GiftWrap.cpp.o

src/Greenhouse/GiftWrap.i: src/Greenhouse/GiftWrap.cpp.i
.PHONY : src/Greenhouse/GiftWrap.i

# target to preprocess a source file
src/Greenhouse/GiftWrap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/GiftWrap.cpp.i
.PHONY : src/Greenhouse/GiftWrap.cpp.i

src/Greenhouse/GiftWrap.s: src/Greenhouse/GiftWrap.cpp.s
.PHONY : src/Greenhouse/GiftWrap.s

# target to generate assembly for a file
src/Greenhouse/GiftWrap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/GiftWrap.cpp.s
.PHONY : src/Greenhouse/GiftWrap.cpp.s

src/Greenhouse/HerbPlant.o: src/Greenhouse/HerbPlant.cpp.o
.PHONY : src/Greenhouse/HerbPlant.o

# target to build an object file
src/Greenhouse/HerbPlant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlant.cpp.o
.PHONY : src/Greenhouse/HerbPlant.cpp.o

src/Greenhouse/HerbPlant.i: src/Greenhouse/HerbPlant.cpp.i
.PHONY : src/Greenhouse/HerbPlant.i

# target to preprocess a source file
src/Greenhouse/HerbPlant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlant.cpp.i
.PHONY : src/Greenhouse/HerbPlant.cpp.i

src/Greenhouse/HerbPlant.s: src/Greenhouse/HerbPlant.cpp.s
.PHONY : src/Greenhouse/HerbPlant.s

# target to generate assembly for a file
src/Greenhouse/HerbPlant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlant.cpp.s
.PHONY : src/Greenhouse/HerbPlant.cpp.s

src/Greenhouse/HerbPlanter.o: src/Greenhouse/HerbPlanter.cpp.o
.PHONY : src/Greenhouse/HerbPlanter.o

# target to build an object file
src/Greenhouse/HerbPlanter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlanter.cpp.o
.PHONY : src/Greenhouse/HerbPlanter.cpp.o

src/Greenhouse/HerbPlanter.i: src/Greenhouse/HerbPlanter.cpp.i
.PHONY : src/Greenhouse/HerbPlanter.i

# target to preprocess a source file
src/Greenhouse/HerbPlanter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlanter.cpp.i
.PHONY : src/Greenhouse/HerbPlanter.cpp.i

src/Greenhouse/HerbPlanter.s: src/Greenhouse/HerbPlanter.cpp.s
.PHONY : src/Greenhouse/HerbPlanter.s

# target to generate assembly for a file
src/Greenhouse/HerbPlanter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbPlanter.cpp.s
.PHONY : src/Greenhouse/HerbPlanter.cpp.s

src/Greenhouse/HerbStrategy.o: src/Greenhouse/HerbStrategy.cpp.o
.PHONY : src/Greenhouse/HerbStrategy.o

# target to build an object file
src/Greenhouse/HerbStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbStrategy.cpp.o
.PHONY : src/Greenhouse/HerbStrategy.cpp.o

src/Greenhouse/HerbStrategy.i: src/Greenhouse/HerbStrategy.cpp.i
.PHONY : src/Greenhouse/HerbStrategy.i

# target to preprocess a source file
src/Greenhouse/HerbStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbStrategy.cpp.i
.PHONY : src/Greenhouse/HerbStrategy.cpp.i

src/Greenhouse/HerbStrategy.s: src/Greenhouse/HerbStrategy.cpp.s
.PHONY : src/Greenhouse/HerbStrategy.s

# target to generate assembly for a file
src/Greenhouse/HerbStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/HerbStrategy.cpp.s
.PHONY : src/Greenhouse/HerbStrategy.cpp.s

src/Greenhouse/Inventory.o: src/Greenhouse/Inventory.cpp.o
.PHONY : src/Greenhouse/Inventory.o

# target to build an object file
src/Greenhouse/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Inventory.cpp.o
.PHONY : src/Greenhouse/Inventory.cpp.o

src/Greenhouse/Inventory.i: src/Greenhouse/Inventory.cpp.i
.PHONY : src/Greenhouse/Inventory.i

# target to preprocess a source file
src/Greenhouse/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Inventory.cpp.i
.PHONY : src/Greenhouse/Inventory.cpp.i

src/Greenhouse/Inventory.s: src/Greenhouse/Inventory.cpp.s
.PHONY : src/Greenhouse/Inventory.s

# target to generate assembly for a file
src/Greenhouse/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Inventory.cpp.s
.PHONY : src/Greenhouse/Inventory.cpp.s

src/Greenhouse/Plant.o: src/Greenhouse/Plant.cpp.o
.PHONY : src/Greenhouse/Plant.o

# target to build an object file
src/Greenhouse/Plant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Plant.cpp.o
.PHONY : src/Greenhouse/Plant.cpp.o

src/Greenhouse/Plant.i: src/Greenhouse/Plant.cpp.i
.PHONY : src/Greenhouse/Plant.i

# target to preprocess a source file
src/Greenhouse/Plant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Plant.cpp.i
.PHONY : src/Greenhouse/Plant.cpp.i

src/Greenhouse/Plant.s: src/Greenhouse/Plant.cpp.s
.PHONY : src/Greenhouse/Plant.s

# target to generate assembly for a file
src/Greenhouse/Plant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Plant.cpp.s
.PHONY : src/Greenhouse/Plant.cpp.s

src/Greenhouse/PlantDecorator.o: src/Greenhouse/PlantDecorator.cpp.o
.PHONY : src/Greenhouse/PlantDecorator.o

# target to build an object file
src/Greenhouse/PlantDecorator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/PlantDecorator.cpp.o
.PHONY : src/Greenhouse/PlantDecorator.cpp.o

src/Greenhouse/PlantDecorator.i: src/Greenhouse/PlantDecorator.cpp.i
.PHONY : src/Greenhouse/PlantDecorator.i

# target to preprocess a source file
src/Greenhouse/PlantDecorator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/PlantDecorator.cpp.i
.PHONY : src/Greenhouse/PlantDecorator.cpp.i

src/Greenhouse/PlantDecorator.s: src/Greenhouse/PlantDecorator.cpp.s
.PHONY : src/Greenhouse/PlantDecorator.s

# target to generate assembly for a file
src/Greenhouse/PlantDecorator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/PlantDecorator.cpp.s
.PHONY : src/Greenhouse/PlantDecorator.cpp.s

src/Greenhouse/Planter.o: src/Greenhouse/Planter.cpp.o
.PHONY : src/Greenhouse/Planter.o

# target to build an object file
src/Greenhouse/Planter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Planter.cpp.o
.PHONY : src/Greenhouse/Planter.cpp.o

src/Greenhouse/Planter.i: src/Greenhouse/Planter.cpp.i
.PHONY : src/Greenhouse/Planter.i

# target to preprocess a source file
src/Greenhouse/Planter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Planter.cpp.i
.PHONY : src/Greenhouse/Planter.cpp.i

src/Greenhouse/Planter.s: src/Greenhouse/Planter.cpp.s
.PHONY : src/Greenhouse/Planter.s

# target to generate assembly for a file
src/Greenhouse/Planter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Planter.cpp.s
.PHONY : src/Greenhouse/Planter.cpp.s

src/Greenhouse/Pot.o: src/Greenhouse/Pot.cpp.o
.PHONY : src/Greenhouse/Pot.o

# target to build an object file
src/Greenhouse/Pot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Pot.cpp.o
.PHONY : src/Greenhouse/Pot.cpp.o

src/Greenhouse/Pot.i: src/Greenhouse/Pot.cpp.i
.PHONY : src/Greenhouse/Pot.i

# target to preprocess a source file
src/Greenhouse/Pot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Pot.cpp.i
.PHONY : src/Greenhouse/Pot.cpp.i

src/Greenhouse/Pot.s: src/Greenhouse/Pot.cpp.s
.PHONY : src/Greenhouse/Pot.s

# target to generate assembly for a file
src/Greenhouse/Pot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Pot.cpp.s
.PHONY : src/Greenhouse/Pot.cpp.s

src/Greenhouse/Prime.o: src/Greenhouse/Prime.cpp.o
.PHONY : src/Greenhouse/Prime.o

# target to build an object file
src/Greenhouse/Prime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Prime.cpp.o
.PHONY : src/Greenhouse/Prime.cpp.o

src/Greenhouse/Prime.i: src/Greenhouse/Prime.cpp.i
.PHONY : src/Greenhouse/Prime.i

# target to preprocess a source file
src/Greenhouse/Prime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Prime.cpp.i
.PHONY : src/Greenhouse/Prime.cpp.i

src/Greenhouse/Prime.s: src/Greenhouse/Prime.cpp.s
.PHONY : src/Greenhouse/Prime.s

# target to generate assembly for a file
src/Greenhouse/Prime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Prime.cpp.s
.PHONY : src/Greenhouse/Prime.cpp.s

src/Greenhouse/RemoveStock.o: src/Greenhouse/RemoveStock.cpp.o
.PHONY : src/Greenhouse/RemoveStock.o

# target to build an object file
src/Greenhouse/RemoveStock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/RemoveStock.cpp.o
.PHONY : src/Greenhouse/RemoveStock.cpp.o

src/Greenhouse/RemoveStock.i: src/Greenhouse/RemoveStock.cpp.i
.PHONY : src/Greenhouse/RemoveStock.i

# target to preprocess a source file
src/Greenhouse/RemoveStock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/RemoveStock.cpp.i
.PHONY : src/Greenhouse/RemoveStock.cpp.i

src/Greenhouse/RemoveStock.s: src/Greenhouse/RemoveStock.cpp.s
.PHONY : src/Greenhouse/RemoveStock.s

# target to generate assembly for a file
src/Greenhouse/RemoveStock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/RemoveStock.cpp.s
.PHONY : src/Greenhouse/RemoveStock.cpp.s

src/Greenhouse/Sapling.o: src/Greenhouse/Sapling.cpp.o
.PHONY : src/Greenhouse/Sapling.o

# target to build an object file
src/Greenhouse/Sapling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Sapling.cpp.o
.PHONY : src/Greenhouse/Sapling.cpp.o

src/Greenhouse/Sapling.i: src/Greenhouse/Sapling.cpp.i
.PHONY : src/Greenhouse/Sapling.i

# target to preprocess a source file
src/Greenhouse/Sapling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Sapling.cpp.i
.PHONY : src/Greenhouse/Sapling.cpp.i

src/Greenhouse/Sapling.s: src/Greenhouse/Sapling.cpp.s
.PHONY : src/Greenhouse/Sapling.s

# target to generate assembly for a file
src/Greenhouse/Sapling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Sapling.cpp.s
.PHONY : src/Greenhouse/Sapling.cpp.s

src/Greenhouse/Seasons.o: src/Greenhouse/Seasons.cpp.o
.PHONY : src/Greenhouse/Seasons.o

# target to build an object file
src/Greenhouse/Seasons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seasons.cpp.o
.PHONY : src/Greenhouse/Seasons.cpp.o

src/Greenhouse/Seasons.i: src/Greenhouse/Seasons.cpp.i
.PHONY : src/Greenhouse/Seasons.i

# target to preprocess a source file
src/Greenhouse/Seasons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seasons.cpp.i
.PHONY : src/Greenhouse/Seasons.cpp.i

src/Greenhouse/Seasons.s: src/Greenhouse/Seasons.cpp.s
.PHONY : src/Greenhouse/Seasons.s

# target to generate assembly for a file
src/Greenhouse/Seasons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seasons.cpp.s
.PHONY : src/Greenhouse/Seasons.cpp.s

src/Greenhouse/Seed.o: src/Greenhouse/Seed.cpp.o
.PHONY : src/Greenhouse/Seed.o

# target to build an object file
src/Greenhouse/Seed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seed.cpp.o
.PHONY : src/Greenhouse/Seed.cpp.o

src/Greenhouse/Seed.i: src/Greenhouse/Seed.cpp.i
.PHONY : src/Greenhouse/Seed.i

# target to preprocess a source file
src/Greenhouse/Seed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seed.cpp.i
.PHONY : src/Greenhouse/Seed.cpp.i

src/Greenhouse/Seed.s: src/Greenhouse/Seed.cpp.s
.PHONY : src/Greenhouse/Seed.s

# target to generate assembly for a file
src/Greenhouse/Seed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Seed.cpp.s
.PHONY : src/Greenhouse/Seed.cpp.s

src/Greenhouse/SpecialArrangement.o: src/Greenhouse/SpecialArrangement.cpp.o
.PHONY : src/Greenhouse/SpecialArrangement.o

# target to build an object file
src/Greenhouse/SpecialArrangement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpecialArrangement.cpp.o
.PHONY : src/Greenhouse/SpecialArrangement.cpp.o

src/Greenhouse/SpecialArrangement.i: src/Greenhouse/SpecialArrangement.cpp.i
.PHONY : src/Greenhouse/SpecialArrangement.i

# target to preprocess a source file
src/Greenhouse/SpecialArrangement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpecialArrangement.cpp.i
.PHONY : src/Greenhouse/SpecialArrangement.cpp.i

src/Greenhouse/SpecialArrangement.s: src/Greenhouse/SpecialArrangement.cpp.s
.PHONY : src/Greenhouse/SpecialArrangement.s

# target to generate assembly for a file
src/Greenhouse/SpecialArrangement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpecialArrangement.cpp.s
.PHONY : src/Greenhouse/SpecialArrangement.cpp.s

src/Greenhouse/Spring.o: src/Greenhouse/Spring.cpp.o
.PHONY : src/Greenhouse/Spring.o

# target to build an object file
src/Greenhouse/Spring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Spring.cpp.o
.PHONY : src/Greenhouse/Spring.cpp.o

src/Greenhouse/Spring.i: src/Greenhouse/Spring.cpp.i
.PHONY : src/Greenhouse/Spring.i

# target to preprocess a source file
src/Greenhouse/Spring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Spring.cpp.i
.PHONY : src/Greenhouse/Spring.cpp.i

src/Greenhouse/Spring.s: src/Greenhouse/Spring.cpp.s
.PHONY : src/Greenhouse/Spring.s

# target to generate assembly for a file
src/Greenhouse/Spring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Spring.cpp.s
.PHONY : src/Greenhouse/Spring.cpp.s

src/Greenhouse/SpringCommand.o: src/Greenhouse/SpringCommand.cpp.o
.PHONY : src/Greenhouse/SpringCommand.o

# target to build an object file
src/Greenhouse/SpringCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpringCommand.cpp.o
.PHONY : src/Greenhouse/SpringCommand.cpp.o

src/Greenhouse/SpringCommand.i: src/Greenhouse/SpringCommand.cpp.i
.PHONY : src/Greenhouse/SpringCommand.i

# target to preprocess a source file
src/Greenhouse/SpringCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpringCommand.cpp.i
.PHONY : src/Greenhouse/SpringCommand.cpp.i

src/Greenhouse/SpringCommand.s: src/Greenhouse/SpringCommand.cpp.s
.PHONY : src/Greenhouse/SpringCommand.s

# target to generate assembly for a file
src/Greenhouse/SpringCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SpringCommand.cpp.s
.PHONY : src/Greenhouse/SpringCommand.cpp.s

src/Greenhouse/StageOfDevelopment.o: src/Greenhouse/StageOfDevelopment.cpp.o
.PHONY : src/Greenhouse/StageOfDevelopment.o

# target to build an object file
src/Greenhouse/StageOfDevelopment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StageOfDevelopment.cpp.o
.PHONY : src/Greenhouse/StageOfDevelopment.cpp.o

src/Greenhouse/StageOfDevelopment.i: src/Greenhouse/StageOfDevelopment.cpp.i
.PHONY : src/Greenhouse/StageOfDevelopment.i

# target to preprocess a source file
src/Greenhouse/StageOfDevelopment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StageOfDevelopment.cpp.i
.PHONY : src/Greenhouse/StageOfDevelopment.cpp.i

src/Greenhouse/StageOfDevelopment.s: src/Greenhouse/StageOfDevelopment.cpp.s
.PHONY : src/Greenhouse/StageOfDevelopment.s

# target to generate assembly for a file
src/Greenhouse/StageOfDevelopment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StageOfDevelopment.cpp.s
.PHONY : src/Greenhouse/StageOfDevelopment.cpp.s

src/Greenhouse/StateCommand.o: src/Greenhouse/StateCommand.cpp.o
.PHONY : src/Greenhouse/StateCommand.o

# target to build an object file
src/Greenhouse/StateCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StateCommand.cpp.o
.PHONY : src/Greenhouse/StateCommand.cpp.o

src/Greenhouse/StateCommand.i: src/Greenhouse/StateCommand.cpp.i
.PHONY : src/Greenhouse/StateCommand.i

# target to preprocess a source file
src/Greenhouse/StateCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StateCommand.cpp.i
.PHONY : src/Greenhouse/StateCommand.cpp.i

src/Greenhouse/StateCommand.s: src/Greenhouse/StateCommand.cpp.s
.PHONY : src/Greenhouse/StateCommand.s

# target to generate assembly for a file
src/Greenhouse/StateCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/StateCommand.cpp.s
.PHONY : src/Greenhouse/StateCommand.cpp.s

src/Greenhouse/Stock.o: src/Greenhouse/Stock.cpp.o
.PHONY : src/Greenhouse/Stock.o

# target to build an object file
src/Greenhouse/Stock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Stock.cpp.o
.PHONY : src/Greenhouse/Stock.cpp.o

src/Greenhouse/Stock.i: src/Greenhouse/Stock.cpp.i
.PHONY : src/Greenhouse/Stock.i

# target to preprocess a source file
src/Greenhouse/Stock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Stock.cpp.i
.PHONY : src/Greenhouse/Stock.cpp.i

src/Greenhouse/Stock.s: src/Greenhouse/Stock.cpp.s
.PHONY : src/Greenhouse/Stock.s

# target to generate assembly for a file
src/Greenhouse/Stock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Stock.cpp.s
.PHONY : src/Greenhouse/Stock.cpp.s

src/Greenhouse/SucculentPlant.o: src/Greenhouse/SucculentPlant.cpp.o
.PHONY : src/Greenhouse/SucculentPlant.o

# target to build an object file
src/Greenhouse/SucculentPlant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlant.cpp.o
.PHONY : src/Greenhouse/SucculentPlant.cpp.o

src/Greenhouse/SucculentPlant.i: src/Greenhouse/SucculentPlant.cpp.i
.PHONY : src/Greenhouse/SucculentPlant.i

# target to preprocess a source file
src/Greenhouse/SucculentPlant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlant.cpp.i
.PHONY : src/Greenhouse/SucculentPlant.cpp.i

src/Greenhouse/SucculentPlant.s: src/Greenhouse/SucculentPlant.cpp.s
.PHONY : src/Greenhouse/SucculentPlant.s

# target to generate assembly for a file
src/Greenhouse/SucculentPlant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlant.cpp.s
.PHONY : src/Greenhouse/SucculentPlant.cpp.s

src/Greenhouse/SucculentPlanter.o: src/Greenhouse/SucculentPlanter.cpp.o
.PHONY : src/Greenhouse/SucculentPlanter.o

# target to build an object file
src/Greenhouse/SucculentPlanter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlanter.cpp.o
.PHONY : src/Greenhouse/SucculentPlanter.cpp.o

src/Greenhouse/SucculentPlanter.i: src/Greenhouse/SucculentPlanter.cpp.i
.PHONY : src/Greenhouse/SucculentPlanter.i

# target to preprocess a source file
src/Greenhouse/SucculentPlanter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlanter.cpp.i
.PHONY : src/Greenhouse/SucculentPlanter.cpp.i

src/Greenhouse/SucculentPlanter.s: src/Greenhouse/SucculentPlanter.cpp.s
.PHONY : src/Greenhouse/SucculentPlanter.s

# target to generate assembly for a file
src/Greenhouse/SucculentPlanter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentPlanter.cpp.s
.PHONY : src/Greenhouse/SucculentPlanter.cpp.s

src/Greenhouse/SucculentStrategy.o: src/Greenhouse/SucculentStrategy.cpp.o
.PHONY : src/Greenhouse/SucculentStrategy.o

# target to build an object file
src/Greenhouse/SucculentStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentStrategy.cpp.o
.PHONY : src/Greenhouse/SucculentStrategy.cpp.o

src/Greenhouse/SucculentStrategy.i: src/Greenhouse/SucculentStrategy.cpp.i
.PHONY : src/Greenhouse/SucculentStrategy.i

# target to preprocess a source file
src/Greenhouse/SucculentStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentStrategy.cpp.i
.PHONY : src/Greenhouse/SucculentStrategy.cpp.i

src/Greenhouse/SucculentStrategy.s: src/Greenhouse/SucculentStrategy.cpp.s
.PHONY : src/Greenhouse/SucculentStrategy.s

# target to generate assembly for a file
src/Greenhouse/SucculentStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SucculentStrategy.cpp.s
.PHONY : src/Greenhouse/SucculentStrategy.cpp.s

src/Greenhouse/Summer.o: src/Greenhouse/Summer.cpp.o
.PHONY : src/Greenhouse/Summer.o

# target to build an object file
src/Greenhouse/Summer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Summer.cpp.o
.PHONY : src/Greenhouse/Summer.cpp.o

src/Greenhouse/Summer.i: src/Greenhouse/Summer.cpp.i
.PHONY : src/Greenhouse/Summer.i

# target to preprocess a source file
src/Greenhouse/Summer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Summer.cpp.i
.PHONY : src/Greenhouse/Summer.cpp.i

src/Greenhouse/Summer.s: src/Greenhouse/Summer.cpp.s
.PHONY : src/Greenhouse/Summer.s

# target to generate assembly for a file
src/Greenhouse/Summer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Summer.cpp.s
.PHONY : src/Greenhouse/Summer.cpp.s

src/Greenhouse/SummerCommand.o: src/Greenhouse/SummerCommand.cpp.o
.PHONY : src/Greenhouse/SummerCommand.o

# target to build an object file
src/Greenhouse/SummerCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SummerCommand.cpp.o
.PHONY : src/Greenhouse/SummerCommand.cpp.o

src/Greenhouse/SummerCommand.i: src/Greenhouse/SummerCommand.cpp.i
.PHONY : src/Greenhouse/SummerCommand.i

# target to preprocess a source file
src/Greenhouse/SummerCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SummerCommand.cpp.i
.PHONY : src/Greenhouse/SummerCommand.cpp.i

src/Greenhouse/SummerCommand.s: src/Greenhouse/SummerCommand.cpp.s
.PHONY : src/Greenhouse/SummerCommand.s

# target to generate assembly for a file
src/Greenhouse/SummerCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/SummerCommand.cpp.s
.PHONY : src/Greenhouse/SummerCommand.cpp.s

src/Greenhouse/TreePlant.o: src/Greenhouse/TreePlant.cpp.o
.PHONY : src/Greenhouse/TreePlant.o

# target to build an object file
src/Greenhouse/TreePlant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlant.cpp.o
.PHONY : src/Greenhouse/TreePlant.cpp.o

src/Greenhouse/TreePlant.i: src/Greenhouse/TreePlant.cpp.i
.PHONY : src/Greenhouse/TreePlant.i

# target to preprocess a source file
src/Greenhouse/TreePlant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlant.cpp.i
.PHONY : src/Greenhouse/TreePlant.cpp.i

src/Greenhouse/TreePlant.s: src/Greenhouse/TreePlant.cpp.s
.PHONY : src/Greenhouse/TreePlant.s

# target to generate assembly for a file
src/Greenhouse/TreePlant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlant.cpp.s
.PHONY : src/Greenhouse/TreePlant.cpp.s

src/Greenhouse/TreePlanter.o: src/Greenhouse/TreePlanter.cpp.o
.PHONY : src/Greenhouse/TreePlanter.o

# target to build an object file
src/Greenhouse/TreePlanter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlanter.cpp.o
.PHONY : src/Greenhouse/TreePlanter.cpp.o

src/Greenhouse/TreePlanter.i: src/Greenhouse/TreePlanter.cpp.i
.PHONY : src/Greenhouse/TreePlanter.i

# target to preprocess a source file
src/Greenhouse/TreePlanter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlanter.cpp.i
.PHONY : src/Greenhouse/TreePlanter.cpp.i

src/Greenhouse/TreePlanter.s: src/Greenhouse/TreePlanter.cpp.s
.PHONY : src/Greenhouse/TreePlanter.s

# target to generate assembly for a file
src/Greenhouse/TreePlanter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreePlanter.cpp.s
.PHONY : src/Greenhouse/TreePlanter.cpp.s

src/Greenhouse/TreeStrategy.o: src/Greenhouse/TreeStrategy.cpp.o
.PHONY : src/Greenhouse/TreeStrategy.o

# target to build an object file
src/Greenhouse/TreeStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreeStrategy.cpp.o
.PHONY : src/Greenhouse/TreeStrategy.cpp.o

src/Greenhouse/TreeStrategy.i: src/Greenhouse/TreeStrategy.cpp.i
.PHONY : src/Greenhouse/TreeStrategy.i

# target to preprocess a source file
src/Greenhouse/TreeStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreeStrategy.cpp.i
.PHONY : src/Greenhouse/TreeStrategy.cpp.i

src/Greenhouse/TreeStrategy.s: src/Greenhouse/TreeStrategy.cpp.s
.PHONY : src/Greenhouse/TreeStrategy.s

# target to generate assembly for a file
src/Greenhouse/TreeStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/TreeStrategy.cpp.s
.PHONY : src/Greenhouse/TreeStrategy.cpp.s

src/Greenhouse/Wilting.o: src/Greenhouse/Wilting.cpp.o
.PHONY : src/Greenhouse/Wilting.o

# target to build an object file
src/Greenhouse/Wilting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Wilting.cpp.o
.PHONY : src/Greenhouse/Wilting.cpp.o

src/Greenhouse/Wilting.i: src/Greenhouse/Wilting.cpp.i
.PHONY : src/Greenhouse/Wilting.i

# target to preprocess a source file
src/Greenhouse/Wilting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Wilting.cpp.i
.PHONY : src/Greenhouse/Wilting.cpp.i

src/Greenhouse/Wilting.s: src/Greenhouse/Wilting.cpp.s
.PHONY : src/Greenhouse/Wilting.s

# target to generate assembly for a file
src/Greenhouse/Wilting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Wilting.cpp.s
.PHONY : src/Greenhouse/Wilting.cpp.s

src/Greenhouse/Winter.o: src/Greenhouse/Winter.cpp.o
.PHONY : src/Greenhouse/Winter.o

# target to build an object file
src/Greenhouse/Winter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Winter.cpp.o
.PHONY : src/Greenhouse/Winter.cpp.o

src/Greenhouse/Winter.i: src/Greenhouse/Winter.cpp.i
.PHONY : src/Greenhouse/Winter.i

# target to preprocess a source file
src/Greenhouse/Winter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Winter.cpp.i
.PHONY : src/Greenhouse/Winter.cpp.i

src/Greenhouse/Winter.s: src/Greenhouse/Winter.cpp.s
.PHONY : src/Greenhouse/Winter.s

# target to generate assembly for a file
src/Greenhouse/Winter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/Winter.cpp.s
.PHONY : src/Greenhouse/Winter.cpp.s

src/Greenhouse/WinterCommand.o: src/Greenhouse/WinterCommand.cpp.o
.PHONY : src/Greenhouse/WinterCommand.o

# target to build an object file
src/Greenhouse/WinterCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/WinterCommand.cpp.o
.PHONY : src/Greenhouse/WinterCommand.cpp.o

src/Greenhouse/WinterCommand.i: src/Greenhouse/WinterCommand.cpp.i
.PHONY : src/Greenhouse/WinterCommand.i

# target to preprocess a source file
src/Greenhouse/WinterCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/WinterCommand.cpp.i
.PHONY : src/Greenhouse/WinterCommand.cpp.i

src/Greenhouse/WinterCommand.s: src/Greenhouse/WinterCommand.cpp.s
.PHONY : src/Greenhouse/WinterCommand.s

# target to generate assembly for a file
src/Greenhouse/WinterCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Greenhouse/WinterCommand.cpp.s
.PHONY : src/Greenhouse/WinterCommand.cpp.s

src/Nursery/Clock.o: src/Nursery/Clock.cpp.o
.PHONY : src/Nursery/Clock.o

# target to build an object file
src/Nursery/Clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Clock.cpp.o
.PHONY : src/Nursery/Clock.cpp.o

src/Nursery/Clock.i: src/Nursery/Clock.cpp.i
.PHONY : src/Nursery/Clock.i

# target to preprocess a source file
src/Nursery/Clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Clock.cpp.i
.PHONY : src/Nursery/Clock.cpp.i

src/Nursery/Clock.s: src/Nursery/Clock.cpp.s
.PHONY : src/Nursery/Clock.s

# target to generate assembly for a file
src/Nursery/Clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Clock.cpp.s
.PHONY : src/Nursery/Clock.cpp.s

src/Nursery/CustomerClock.o: src/Nursery/CustomerClock.cpp.o
.PHONY : src/Nursery/CustomerClock.o

# target to build an object file
src/Nursery/CustomerClock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/CustomerClock.cpp.o
.PHONY : src/Nursery/CustomerClock.cpp.o

src/Nursery/CustomerClock.i: src/Nursery/CustomerClock.cpp.i
.PHONY : src/Nursery/CustomerClock.i

# target to preprocess a source file
src/Nursery/CustomerClock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/CustomerClock.cpp.i
.PHONY : src/Nursery/CustomerClock.cpp.i

src/Nursery/CustomerClock.s: src/Nursery/CustomerClock.cpp.s
.PHONY : src/Nursery/CustomerClock.s

# target to generate assembly for a file
src/Nursery/CustomerClock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/CustomerClock.cpp.s
.PHONY : src/Nursery/CustomerClock.cpp.s

src/Nursery/Nursery.o: src/Nursery/Nursery.cpp.o
.PHONY : src/Nursery/Nursery.o

# target to build an object file
src/Nursery/Nursery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Nursery.cpp.o
.PHONY : src/Nursery/Nursery.cpp.o

src/Nursery/Nursery.i: src/Nursery/Nursery.cpp.i
.PHONY : src/Nursery/Nursery.i

# target to preprocess a source file
src/Nursery/Nursery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Nursery.cpp.i
.PHONY : src/Nursery/Nursery.cpp.i

src/Nursery/Nursery.s: src/Nursery/Nursery.cpp.s
.PHONY : src/Nursery/Nursery.s

# target to generate assembly for a file
src/Nursery/Nursery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/Nursery.cpp.s
.PHONY : src/Nursery/Nursery.cpp.s

src/Nursery/PlantClock.o: src/Nursery/PlantClock.cpp.o
.PHONY : src/Nursery/PlantClock.o

# target to build an object file
src/Nursery/PlantClock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/PlantClock.cpp.o
.PHONY : src/Nursery/PlantClock.cpp.o

src/Nursery/PlantClock.i: src/Nursery/PlantClock.cpp.i
.PHONY : src/Nursery/PlantClock.i

# target to preprocess a source file
src/Nursery/PlantClock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/PlantClock.cpp.i
.PHONY : src/Nursery/PlantClock.cpp.i

src/Nursery/PlantClock.s: src/Nursery/PlantClock.cpp.s
.PHONY : src/Nursery/PlantClock.s

# target to generate assembly for a file
src/Nursery/PlantClock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/PlantClock.cpp.s
.PHONY : src/Nursery/PlantClock.cpp.s

src/Nursery/SeasonClock.o: src/Nursery/SeasonClock.cpp.o
.PHONY : src/Nursery/SeasonClock.o

# target to build an object file
src/Nursery/SeasonClock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/SeasonClock.cpp.o
.PHONY : src/Nursery/SeasonClock.cpp.o

src/Nursery/SeasonClock.i: src/Nursery/SeasonClock.cpp.i
.PHONY : src/Nursery/SeasonClock.i

# target to preprocess a source file
src/Nursery/SeasonClock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/SeasonClock.cpp.i
.PHONY : src/Nursery/SeasonClock.cpp.i

src/Nursery/SeasonClock.s: src/Nursery/SeasonClock.cpp.s
.PHONY : src/Nursery/SeasonClock.s

# target to generate assembly for a file
src/Nursery/SeasonClock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Nursery/SeasonClock.cpp.s
.PHONY : src/Nursery/SeasonClock.cpp.s

src/Staff/Available.o: src/Staff/Available.cpp.o
.PHONY : src/Staff/Available.o

# target to build an object file
src/Staff/Available.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Available.cpp.o
.PHONY : src/Staff/Available.cpp.o

src/Staff/Available.i: src/Staff/Available.cpp.i
.PHONY : src/Staff/Available.i

# target to preprocess a source file
src/Staff/Available.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Available.cpp.i
.PHONY : src/Staff/Available.cpp.i

src/Staff/Available.s: src/Staff/Available.cpp.s
.PHONY : src/Staff/Available.s

# target to generate assembly for a file
src/Staff/Available.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Available.cpp.s
.PHONY : src/Staff/Available.cpp.s

src/Staff/Busy.o: src/Staff/Busy.cpp.o
.PHONY : src/Staff/Busy.o

# target to build an object file
src/Staff/Busy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Busy.cpp.o
.PHONY : src/Staff/Busy.cpp.o

src/Staff/Busy.i: src/Staff/Busy.cpp.i
.PHONY : src/Staff/Busy.i

# target to preprocess a source file
src/Staff/Busy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Busy.cpp.i
.PHONY : src/Staff/Busy.cpp.i

src/Staff/Busy.s: src/Staff/Busy.cpp.s
.PHONY : src/Staff/Busy.s

# target to generate assembly for a file
src/Staff/Busy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Busy.cpp.s
.PHONY : src/Staff/Busy.cpp.s

src/Staff/Cashiers.o: src/Staff/Cashiers.cpp.o
.PHONY : src/Staff/Cashiers.o

# target to build an object file
src/Staff/Cashiers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Cashiers.cpp.o
.PHONY : src/Staff/Cashiers.cpp.o

src/Staff/Cashiers.i: src/Staff/Cashiers.cpp.i
.PHONY : src/Staff/Cashiers.i

# target to preprocess a source file
src/Staff/Cashiers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Cashiers.cpp.i
.PHONY : src/Staff/Cashiers.cpp.i

src/Staff/Cashiers.s: src/Staff/Cashiers.cpp.s
.PHONY : src/Staff/Cashiers.s

# target to generate assembly for a file
src/Staff/Cashiers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Cashiers.cpp.s
.PHONY : src/Staff/Cashiers.cpp.s

src/Staff/FindAvailableStaff.o: src/Staff/FindAvailableStaff.cpp.o
.PHONY : src/Staff/FindAvailableStaff.o

# target to build an object file
src/Staff/FindAvailableStaff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/FindAvailableStaff.cpp.o
.PHONY : src/Staff/FindAvailableStaff.cpp.o

src/Staff/FindAvailableStaff.i: src/Staff/FindAvailableStaff.cpp.i
.PHONY : src/Staff/FindAvailableStaff.i

# target to preprocess a source file
src/Staff/FindAvailableStaff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/FindAvailableStaff.cpp.i
.PHONY : src/Staff/FindAvailableStaff.cpp.i

src/Staff/FindAvailableStaff.s: src/Staff/FindAvailableStaff.cpp.s
.PHONY : src/Staff/FindAvailableStaff.s

# target to generate assembly for a file
src/Staff/FindAvailableStaff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/FindAvailableStaff.cpp.s
.PHONY : src/Staff/FindAvailableStaff.cpp.s

src/Staff/Gardener.o: src/Staff/Gardener.cpp.o
.PHONY : src/Staff/Gardener.o

# target to build an object file
src/Staff/Gardener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Gardener.cpp.o
.PHONY : src/Staff/Gardener.cpp.o

src/Staff/Gardener.i: src/Staff/Gardener.cpp.i
.PHONY : src/Staff/Gardener.i

# target to preprocess a source file
src/Staff/Gardener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Gardener.cpp.i
.PHONY : src/Staff/Gardener.cpp.i

src/Staff/Gardener.s: src/Staff/Gardener.cpp.s
.PHONY : src/Staff/Gardener.s

# target to generate assembly for a file
src/Staff/Gardener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Gardener.cpp.s
.PHONY : src/Staff/Gardener.cpp.s

src/Staff/InfoDesk.o: src/Staff/InfoDesk.cpp.o
.PHONY : src/Staff/InfoDesk.o

# target to build an object file
src/Staff/InfoDesk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/InfoDesk.cpp.o
.PHONY : src/Staff/InfoDesk.cpp.o

src/Staff/InfoDesk.i: src/Staff/InfoDesk.cpp.i
.PHONY : src/Staff/InfoDesk.i

# target to preprocess a source file
src/Staff/InfoDesk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/InfoDesk.cpp.i
.PHONY : src/Staff/InfoDesk.cpp.i

src/Staff/InfoDesk.s: src/Staff/InfoDesk.cpp.s
.PHONY : src/Staff/InfoDesk.s

# target to generate assembly for a file
src/Staff/InfoDesk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/InfoDesk.cpp.s
.PHONY : src/Staff/InfoDesk.cpp.s

src/Staff/Manager.o: src/Staff/Manager.cpp.o
.PHONY : src/Staff/Manager.o

# target to build an object file
src/Staff/Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Manager.cpp.o
.PHONY : src/Staff/Manager.cpp.o

src/Staff/Manager.i: src/Staff/Manager.cpp.i
.PHONY : src/Staff/Manager.i

# target to preprocess a source file
src/Staff/Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Manager.cpp.i
.PHONY : src/Staff/Manager.cpp.i

src/Staff/Manager.s: src/Staff/Manager.cpp.s
.PHONY : src/Staff/Manager.s

# target to generate assembly for a file
src/Staff/Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Manager.cpp.s
.PHONY : src/Staff/Manager.cpp.s

src/Staff/SalesStaff.o: src/Staff/SalesStaff.cpp.o
.PHONY : src/Staff/SalesStaff.o

# target to build an object file
src/Staff/SalesStaff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/SalesStaff.cpp.o
.PHONY : src/Staff/SalesStaff.cpp.o

src/Staff/SalesStaff.i: src/Staff/SalesStaff.cpp.i
.PHONY : src/Staff/SalesStaff.i

# target to preprocess a source file
src/Staff/SalesStaff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/SalesStaff.cpp.i
.PHONY : src/Staff/SalesStaff.cpp.i

src/Staff/SalesStaff.s: src/Staff/SalesStaff.cpp.s
.PHONY : src/Staff/SalesStaff.s

# target to generate assembly for a file
src/Staff/SalesStaff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/SalesStaff.cpp.s
.PHONY : src/Staff/SalesStaff.cpp.s

src/Staff/Staff.o: src/Staff/Staff.cpp.o
.PHONY : src/Staff/Staff.o

# target to build an object file
src/Staff/Staff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Staff.cpp.o
.PHONY : src/Staff/Staff.cpp.o

src/Staff/Staff.i: src/Staff/Staff.cpp.i
.PHONY : src/Staff/Staff.i

# target to preprocess a source file
src/Staff/Staff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Staff.cpp.i
.PHONY : src/Staff/Staff.cpp.i

src/Staff/Staff.s: src/Staff/Staff.cpp.s
.PHONY : src/Staff/Staff.s

# target to generate assembly for a file
src/Staff/Staff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/Staff.cpp.s
.PHONY : src/Staff/Staff.cpp.s

src/Staff/StaffState.o: src/Staff/StaffState.cpp.o
.PHONY : src/Staff/StaffState.o

# target to build an object file
src/Staff/StaffState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/StaffState.cpp.o
.PHONY : src/Staff/StaffState.cpp.o

src/Staff/StaffState.i: src/Staff/StaffState.cpp.i
.PHONY : src/Staff/StaffState.i

# target to preprocess a source file
src/Staff/StaffState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/StaffState.cpp.i
.PHONY : src/Staff/StaffState.cpp.i

src/Staff/StaffState.s: src/Staff/StaffState.cpp.s
.PHONY : src/Staff/StaffState.s

# target to generate assembly for a file
src/Staff/StaffState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project_lib.dir/build.make CMakeFiles/project_lib.dir/src/Staff/StaffState.cpp.s
.PHONY : src/Staff/StaffState.cpp.s

tests/test_customer.o: tests/test_customer.cpp.o
.PHONY : tests/test_customer.o

# target to build an object file
tests/test_customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_customer.cpp.o
.PHONY : tests/test_customer.cpp.o

tests/test_customer.i: tests/test_customer.cpp.i
.PHONY : tests/test_customer.i

# target to preprocess a source file
tests/test_customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_customer.cpp.i
.PHONY : tests/test_customer.cpp.i

tests/test_customer.s: tests/test_customer.cpp.s
.PHONY : tests/test_customer.s

# target to generate assembly for a file
tests/test_customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_customer.cpp.s
.PHONY : tests/test_customer.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Nursery_autogen"
	@echo "... Nursery_autogen_timestamp_deps"
	@echo "... gmock_autogen"
	@echo "... gmock_autogen_timestamp_deps"
	@echo "... gmock_main_autogen"
	@echo "... gmock_main_autogen_timestamp_deps"
	@echo "... gtest_autogen"
	@echo "... gtest_autogen_timestamp_deps"
	@echo "... gtest_main_autogen"
	@echo "... gtest_main_autogen_timestamp_deps"
	@echo "... project_lib_autogen"
	@echo "... project_lib_autogen_timestamp_deps"
	@echo "... run_tests_autogen"
	@echo "... run_tests_autogen_timestamp_deps"
	@echo "... Nursery"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... project_lib"
	@echo "... run_tests"
	@echo "... project_lib_autogen/mocs_compilation.o"
	@echo "... project_lib_autogen/mocs_compilation.i"
	@echo "... project_lib_autogen/mocs_compilation.s"
	@echo "... run_tests_autogen/mocs_compilation.o"
	@echo "... run_tests_autogen/mocs_compilation.i"
	@echo "... run_tests_autogen/mocs_compilation.s"
	@echo "... src/Customer/Browse.o"
	@echo "... src/Customer/Browse.i"
	@echo "... src/Customer/Browse.s"
	@echo "... src/Customer/Customer.o"
	@echo "... src/Customer/Customer.i"
	@echo "... src/Customer/Customer.s"
	@echo "... src/Customer/CustomerCreator.o"
	@echo "... src/Customer/CustomerCreator.i"
	@echo "... src/Customer/CustomerCreator.s"
	@echo "... src/Customer/Enquire.o"
	@echo "... src/Customer/Enquire.i"
	@echo "... src/Customer/Enquire.s"
	@echo "... src/Customer/Purchasing.o"
	@echo "... src/Customer/Purchasing.i"
	@echo "... src/Customer/Purchasing.s"
	@echo "... src/Greenhouse/AddStock.o"
	@echo "... src/Greenhouse/AddStock.i"
	@echo "... src/Greenhouse/AddStock.s"
	@echo "... src/Greenhouse/Autumn.o"
	@echo "... src/Greenhouse/Autumn.i"
	@echo "... src/Greenhouse/Autumn.s"
	@echo "... src/Greenhouse/AutumnCommand.o"
	@echo "... src/Greenhouse/AutumnCommand.i"
	@echo "... src/Greenhouse/AutumnCommand.s"
	@echo "... src/Greenhouse/CareStrategy.o"
	@echo "... src/Greenhouse/CareStrategy.i"
	@echo "... src/Greenhouse/CareStrategy.s"
	@echo "... src/Greenhouse/Command.o"
	@echo "... src/Greenhouse/Command.i"
	@echo "... src/Greenhouse/Command.s"
	@echo "... src/Greenhouse/Dead.o"
	@echo "... src/Greenhouse/Dead.i"
	@echo "... src/Greenhouse/Dead.s"
	@echo "... src/Greenhouse/FlowerPlant.o"
	@echo "... src/Greenhouse/FlowerPlant.i"
	@echo "... src/Greenhouse/FlowerPlant.s"
	@echo "... src/Greenhouse/FlowerPlanter.o"
	@echo "... src/Greenhouse/FlowerPlanter.i"
	@echo "... src/Greenhouse/FlowerPlanter.s"
	@echo "... src/Greenhouse/FlowerStrategy.o"
	@echo "... src/Greenhouse/FlowerStrategy.i"
	@echo "... src/Greenhouse/FlowerStrategy.s"
	@echo "... src/Greenhouse/GiftWrap.o"
	@echo "... src/Greenhouse/GiftWrap.i"
	@echo "... src/Greenhouse/GiftWrap.s"
	@echo "... src/Greenhouse/HerbPlant.o"
	@echo "... src/Greenhouse/HerbPlant.i"
	@echo "... src/Greenhouse/HerbPlant.s"
	@echo "... src/Greenhouse/HerbPlanter.o"
	@echo "... src/Greenhouse/HerbPlanter.i"
	@echo "... src/Greenhouse/HerbPlanter.s"
	@echo "... src/Greenhouse/HerbStrategy.o"
	@echo "... src/Greenhouse/HerbStrategy.i"
	@echo "... src/Greenhouse/HerbStrategy.s"
	@echo "... src/Greenhouse/Inventory.o"
	@echo "... src/Greenhouse/Inventory.i"
	@echo "... src/Greenhouse/Inventory.s"
	@echo "... src/Greenhouse/Plant.o"
	@echo "... src/Greenhouse/Plant.i"
	@echo "... src/Greenhouse/Plant.s"
	@echo "... src/Greenhouse/PlantDecorator.o"
	@echo "... src/Greenhouse/PlantDecorator.i"
	@echo "... src/Greenhouse/PlantDecorator.s"
	@echo "... src/Greenhouse/Planter.o"
	@echo "... src/Greenhouse/Planter.i"
	@echo "... src/Greenhouse/Planter.s"
	@echo "... src/Greenhouse/Pot.o"
	@echo "... src/Greenhouse/Pot.i"
	@echo "... src/Greenhouse/Pot.s"
	@echo "... src/Greenhouse/Prime.o"
	@echo "... src/Greenhouse/Prime.i"
	@echo "... src/Greenhouse/Prime.s"
	@echo "... src/Greenhouse/RemoveStock.o"
	@echo "... src/Greenhouse/RemoveStock.i"
	@echo "... src/Greenhouse/RemoveStock.s"
	@echo "... src/Greenhouse/Sapling.o"
	@echo "... src/Greenhouse/Sapling.i"
	@echo "... src/Greenhouse/Sapling.s"
	@echo "... src/Greenhouse/Seasons.o"
	@echo "... src/Greenhouse/Seasons.i"
	@echo "... src/Greenhouse/Seasons.s"
	@echo "... src/Greenhouse/Seed.o"
	@echo "... src/Greenhouse/Seed.i"
	@echo "... src/Greenhouse/Seed.s"
	@echo "... src/Greenhouse/SpecialArrangement.o"
	@echo "... src/Greenhouse/SpecialArrangement.i"
	@echo "... src/Greenhouse/SpecialArrangement.s"
	@echo "... src/Greenhouse/Spring.o"
	@echo "... src/Greenhouse/Spring.i"
	@echo "... src/Greenhouse/Spring.s"
	@echo "... src/Greenhouse/SpringCommand.o"
	@echo "... src/Greenhouse/SpringCommand.i"
	@echo "... src/Greenhouse/SpringCommand.s"
	@echo "... src/Greenhouse/StageOfDevelopment.o"
	@echo "... src/Greenhouse/StageOfDevelopment.i"
	@echo "... src/Greenhouse/StageOfDevelopment.s"
	@echo "... src/Greenhouse/StateCommand.o"
	@echo "... src/Greenhouse/StateCommand.i"
	@echo "... src/Greenhouse/StateCommand.s"
	@echo "... src/Greenhouse/Stock.o"
	@echo "... src/Greenhouse/Stock.i"
	@echo "... src/Greenhouse/Stock.s"
	@echo "... src/Greenhouse/SucculentPlant.o"
	@echo "... src/Greenhouse/SucculentPlant.i"
	@echo "... src/Greenhouse/SucculentPlant.s"
	@echo "... src/Greenhouse/SucculentPlanter.o"
	@echo "... src/Greenhouse/SucculentPlanter.i"
	@echo "... src/Greenhouse/SucculentPlanter.s"
	@echo "... src/Greenhouse/SucculentStrategy.o"
	@echo "... src/Greenhouse/SucculentStrategy.i"
	@echo "... src/Greenhouse/SucculentStrategy.s"
	@echo "... src/Greenhouse/Summer.o"
	@echo "... src/Greenhouse/Summer.i"
	@echo "... src/Greenhouse/Summer.s"
	@echo "... src/Greenhouse/SummerCommand.o"
	@echo "... src/Greenhouse/SummerCommand.i"
	@echo "... src/Greenhouse/SummerCommand.s"
	@echo "... src/Greenhouse/TreePlant.o"
	@echo "... src/Greenhouse/TreePlant.i"
	@echo "... src/Greenhouse/TreePlant.s"
	@echo "... src/Greenhouse/TreePlanter.o"
	@echo "... src/Greenhouse/TreePlanter.i"
	@echo "... src/Greenhouse/TreePlanter.s"
	@echo "... src/Greenhouse/TreeStrategy.o"
	@echo "... src/Greenhouse/TreeStrategy.i"
	@echo "... src/Greenhouse/TreeStrategy.s"
	@echo "... src/Greenhouse/Wilting.o"
	@echo "... src/Greenhouse/Wilting.i"
	@echo "... src/Greenhouse/Wilting.s"
	@echo "... src/Greenhouse/Winter.o"
	@echo "... src/Greenhouse/Winter.i"
	@echo "... src/Greenhouse/Winter.s"
	@echo "... src/Greenhouse/WinterCommand.o"
	@echo "... src/Greenhouse/WinterCommand.i"
	@echo "... src/Greenhouse/WinterCommand.s"
	@echo "... src/Nursery/Clock.o"
	@echo "... src/Nursery/Clock.i"
	@echo "... src/Nursery/Clock.s"
	@echo "... src/Nursery/CustomerClock.o"
	@echo "... src/Nursery/CustomerClock.i"
	@echo "... src/Nursery/CustomerClock.s"
	@echo "... src/Nursery/Nursery.o"
	@echo "... src/Nursery/Nursery.i"
	@echo "... src/Nursery/Nursery.s"
	@echo "... src/Nursery/PlantClock.o"
	@echo "... src/Nursery/PlantClock.i"
	@echo "... src/Nursery/PlantClock.s"
	@echo "... src/Nursery/SeasonClock.o"
	@echo "... src/Nursery/SeasonClock.i"
	@echo "... src/Nursery/SeasonClock.s"
	@echo "... src/Staff/Available.o"
	@echo "... src/Staff/Available.i"
	@echo "... src/Staff/Available.s"
	@echo "... src/Staff/Busy.o"
	@echo "... src/Staff/Busy.i"
	@echo "... src/Staff/Busy.s"
	@echo "... src/Staff/Cashiers.o"
	@echo "... src/Staff/Cashiers.i"
	@echo "... src/Staff/Cashiers.s"
	@echo "... src/Staff/FindAvailableStaff.o"
	@echo "... src/Staff/FindAvailableStaff.i"
	@echo "... src/Staff/FindAvailableStaff.s"
	@echo "... src/Staff/Gardener.o"
	@echo "... src/Staff/Gardener.i"
	@echo "... src/Staff/Gardener.s"
	@echo "... src/Staff/InfoDesk.o"
	@echo "... src/Staff/InfoDesk.i"
	@echo "... src/Staff/InfoDesk.s"
	@echo "... src/Staff/Manager.o"
	@echo "... src/Staff/Manager.i"
	@echo "... src/Staff/Manager.s"
	@echo "... src/Staff/SalesStaff.o"
	@echo "... src/Staff/SalesStaff.i"
	@echo "... src/Staff/SalesStaff.s"
	@echo "... src/Staff/Staff.o"
	@echo "... src/Staff/Staff.i"
	@echo "... src/Staff/Staff.s"
	@echo "... src/Staff/StaffState.o"
	@echo "... src/Staff/StaffState.i"
	@echo "... src/Staff/StaffState.s"
	@echo "... tests/test_customer.o"
	@echo "... tests/test_customer.i"
	@echo "... tests/test_customer.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

