if(EXISTS "/home/langa/project214/Chaos_Compilers_COS214_Project_2025/run_tests[1]_tests.cmake")
  include("/home/langa/project214/Chaos_Compilers_COS214_Project_2025/run_tests[1]_tests.cmake")
else()
  add_test(run_tests_NOT_BUILT run_tests_NOT_BUILT)
endif()
